---
build_matrix:
  linux:
readme_file: frontend/help.md
triggers:
  - github.com/Luzifer/gobuilder/cmd/starter
  - github.com/Luzifer/gobuilder/cmd/gobuilder-cli
artifacts:
  - frontend
notify:
  - type: pushover
    target: U2FsdGVkX1+lhqGpqB/a9C300iOul5tdRcg1Fb7vwivoJA64eNfFVTL+QwDl5wT8
  - type: email
    target: U2FsdGVkX194oB3+U15z7t9iKbVxGjFWb7gjvo0R8NM=
